config/urls.py
from django.contrib import admin
from django.urls import path, include

from poll import views


def view(args):
    pass


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('poll/', include('poll.urls'))
]

poll/urls.py
from django.urls import path
from poll import views

app_name = 'poll'

urlpatterns = [
    # poll/
    path('', views.index, name='poll'),
    # poll/<int:question_id>/
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/result/', views.result, name='result'),
]

poll/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

poll/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from poll.models import Question

# 127.0.0.1:8000/poll - 전체 목록
def index(request):
    question_list = Question.objects.all()
    context = {'question_list': question_list}
    return render(request, 'poll/index.html', context)
    # return HttpResponse("안녕하세요~ django!")

# 127.0.0.1:8000/poll/1 - 1개 정보
def detail(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)  # pk : primary key
    context = {'question': question}
    return render(request, 'poll/detail.html', context)
    # return HttpResponse("You are looking at question %s." % question_id)

# 127.0.0.1:8000/poll/2/vote
def vote(request, question_id):
    try:
        # question = Question.objects.get(id=question_id)
        question = get_object_or_404(Question, pk=question_id)
        choice = request.POST['choice']    # name에서 가져오기
        sel_choice = question.choice_set.get(id=choice)
    except KeyError:
        return render(request, 'poll/detail.html', {
            'question': question,
            'error_message': '항목을 선택 해주세요'
        })
    else:
        sel_choice.votes += 1
        sel_choice.save()
        return HttpResponseRedirect(reverse('poll:result', args=(question_id,)))

# 127.0.0.1:8000/poll/2/results
def result(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'poll/result.html', context)

templates/poll/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>설문 항목 투표</title>
    <link rel="stylesheet" href="{% static 'poll/css/style.css' %}">
</head>
<body>
    <div id="container">
        <section>
            <form action="{% url 'poll:vote' question.id %}" method="post" class="form_vote">
                {% csrf_token %}
                <fieldset>
                    <legend><h3>{{ question.question_text }}</h3></legend>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    {% for choice in question.choice_set.all %}
                    <p>
                        <input type="radio" name="choice" id="choice{{ forloop.counter }}"
                            value="{{ choice.id }}">
                        <label for="choice{{ forloop.counter }}"> {{ choice.choice_text }}</label>
                    {% endfor %}
                </fieldset>
                <p><input type="submit" value="투표"></p>
            </form>
        </section>
    </div>
</body>
</html>

templates/poll/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>index 페이지</title>
    <link rel="stylesheet" href="{% static 'poll/css/style.css' %}">
</head>
<body>
    <div id="container">
        <section>
            <h2>설문 목록</h2>
            <ul>
            {% for question in question_list %}
                <li>
                    <a href="{% url 'poll:detail' question.id %}">{{ question.question_text }}</a>
                </li>
            {% endfor %}
            </ul>
        </section>
    </div>
</body>
</html>

templates/poll/result.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>투표 결과</title>
    <link rel="stylesheet" href="{% static 'poll/css/style.css' %}">
</head>
<body>
    <div id="container">
        <section id="result">
            <h2>{{ question.question_text }}</h2>
            <ul>
                {% for choice in question.choice_set.all %}
                <li>
                    {{ choice.choice_text }} -- {{ choice.votes }} vote
                </li>
                {% endfor %}
            </ul>
            <div class="vote">
                <a href="{% url 'poll:detail' question.id %}" class="button">다시 투표하시겠습니까?</a>
            </div>
        </section>
    </div>
</body>
</html>